# Generated by Django 2.2 on 2021-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('mobile_no', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
